import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#2B2D42", // Matches header color to fix status bar
    },
    listArea: {
        flex: 1,
        backgroundColor: "#EDF2F4",
        borderTopLeftRadius: 35,
        borderTopRightRadius: 35,
        marginTop: -35,
        paddingTop: 10,
    },
    header: {
        paddingHorizontal: 20,
        paddingBottom: 50, // Increased for overlap
        backgroundColor: "#2B2D42",
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 10,
    },
    backButton: {
        marginRight: 15,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#FFF",
        flex: 1,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 10,
        paddingHorizontal: 12,
        marginTop: 15,
        height: 40,
    },
    searchBar: {
        flex: 1,
        color: '#FFF',
        fontSize: 14,
        marginLeft: 8,
    },
    listContent: {
        padding: 15,
    },
    card: {
        backgroundColor: '#FFF',
        borderRadius: 15,
        marginBottom: 10,
        padding: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
        width: '48.5%', // Slightly less than half
        alignItems: 'center',
    },
    cardOutItem: {
        opacity: 0.6,
    },
    productImage: {
        width: '100%',
        height: 100,
        borderRadius: 10,
        backgroundColor: '#EDF2F4',
        marginBottom: 8,
    },
    imagePlaceholder: {
        width: '100%',
        height: 100,
        borderRadius: 10,
        backgroundColor: '#EDF2F4',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    infoContainer: {
        width: '100%',
        alignItems: 'center',
    },
    productName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2B2D42',
        marginBottom: 4,
    },
    outOfStockText: {
        color: '#D90429',
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    productBarcode: {
        fontSize: 12,
        color: '#8D99AE',
    },
    stockControls: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        justifyContent: 'center',
        width: '100%',
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        width: '100%',
        marginTop: 5,
    },
    miniControlButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#EDF2F4',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 5,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 50,
    },
    emptyText: {
        fontSize: 16,
        color: '#8D99AE',
        marginTop: 10,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        width: '100%',
        maxHeight: '90%',
        backgroundColor: '#FFF',
        borderRadius: 20,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
    },
    closeButton: {
        position: 'absolute',
        top: 15,
        right: 15,
        zIndex: 1,
        backgroundColor: '#F8F9FA',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailImage: {
        width: '100%',
        height: 250,
        borderRadius: 15,
        marginBottom: 20,
    },
    detailPlaceholder: {
        width: '100%',
        height: 250,
        borderRadius: 15,
        backgroundColor: '#EDF2F4',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    detailInfo: {
        width: '100%',
    },
    detailName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2B2D42',
        marginBottom: 8,
        textAlign: 'center',
    },
    detailBrand: {
        fontSize: 18,
        color: '#D90429',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 15,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#EDF2F4',
    },
    detailLabel: {
        fontSize: 14,
        color: '#8D99AE',
    },
    detailValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2B2D42',
    },
    modalQuantityControls: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
    },
    modalStockValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2B2D42',
        marginHorizontal: 10,
        minWidth: 60,
        textAlign: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 8,
        paddingVertical: 5,
    },
    modalControlButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#EDF2F4',
        justifyContent: 'center',
        alignItems: 'center',
    },
    confirmButton: {
        backgroundColor: '#D90429',
        borderRadius: 12,
        paddingVertical: 15,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
    },
    confirmButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
});
