import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#2B2D42",
    },
    contentArea: {
        flex: 1,
        backgroundColor: "#EDF2F4",
        borderTopLeftRadius: 35,
        borderTopRightRadius: 35,
        marginTop: -35,
        paddingTop: 10,
    },
    topBar: {
        width: "100%",
        backgroundColor: "#2B2D42",
        justifyContent: "center",
        alignItems: "center",
        paddingBottom: 60, // Increased to account for contentArea overlap
        paddingTop: 10,
        borderBottomLeftRadius: 0, // Removed since contentArea overlaps
        borderBottomRightRadius: 0,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 10,
    },
    topImage: {
        width: "80%",
        height: 80,
        resizeMode: "contain",
    },
    searchContainer: {
        flexDirection: "row",
        alignItems: "center",
        width: '90%',
        marginTop: 15,
        backgroundColor: "#FFF",
        borderRadius: 15,
        paddingHorizontal: 15,
        height: 55,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },
    searchBar: {
        flex: 1,
        height: "100%",
        marginLeft: 10,
        fontSize: 16,
        color: "#2B2D42",
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#2B2D42",
        textAlign: "left",
        marginHorizontal: 20,
        marginVertical: 20,
        letterSpacing: -0.5,
    },
    cardsContainer: {
        paddingHorizontal: 15,
        paddingTop: 10,
    },
    cardsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginBottom: 15,
    },
    addButton: {
        backgroundColor: "#D90429",
        height: 55,
        borderRadius: 15,
        flexDirection: 'row',
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#D90429",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
    addButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
});
