import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        backgroundColor: "#EDF2F4",
        padding: 20,
    },
    title: {
        fontSize: 28,
        fontWeight: "bold",
        marginBottom: 30,
        color: "#2B2D42",
        textAlign: "left",
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        color: "#8D99AE",
        marginBottom: 8,
        fontWeight: "600",
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    input: {
        backgroundColor: "#FFF",
        borderRadius: 12,
        padding: 15,
        fontSize: 16,
        color: "#2B2D42",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    scanButton: {
        flexDirection: "row",
        backgroundColor: "#2B2D42",
        padding: 16,
        borderRadius: 15,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 25,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    scanButtonText: {
        color: "#FFF",
        fontSize: 16,
        fontWeight: "bold",
        marginLeft: 10,
    },
    quantityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 5,
        alignSelf: 'flex-start',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    quantityButton: {
        width: 45,
        height: 45,
        borderRadius: 10,
        backgroundColor: '#EDF2F4',
        justifyContent: 'center',
        alignItems: 'center',
    },
    quantityValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2B2D42',
        marginHorizontal: 20,
        minWidth: 30,
        textAlign: 'center',
    },
    imageButton: {
        backgroundColor: "#FFF",
        height: 180,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 30,
        overflow: "hidden",
        borderWidth: 2,
        borderColor: '#8D99AE',
        borderStyle: 'dashed',
    },
    productImage: {
        width: "100%",
        height: "100%",
    },
    imagePlaceholderText: {
        color: "#8D99AE",
        marginTop: 10,
        fontWeight: '500',
    },
    saveButton: {
        backgroundColor: "#D90429",
        padding: 18,
        borderRadius: 15,
        alignItems: "center",
        marginTop: 10,
        shadowColor: "#D90429",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 6,
    },
    saveButtonText: {
        color: "#FFF",
        fontSize: 18,
        fontWeight: "bold",
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    cameraContainer: {
        flex: 1,
        backgroundColor: 'black',
    },
    camera: {
        flex: 1,
    },
    closeCameraButton: {
        position: 'absolute',
        top: 50,
        right: 20,
        backgroundColor: 'rgba(0,0,0,0.5)',
        padding: 10,
        borderRadius: 20,
    },
    closeCameraText: {
        color: 'white',
        fontSize: 14,
        fontWeight: 'bold',
    },
    categoryContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    categoryChip: {
        paddingHorizontal: 15,
        paddingVertical: 10,
        backgroundColor: '#FFF',
        borderRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    categoryChipSelected: {
        backgroundColor: '#D90429',
    },
    categoryText: {
        color: '#8D99AE',
        fontSize: 12,
        fontWeight: '600',
    },
    categoryTextSelected: {
        color: '#FFF',
    },
});
